# @package _global_

module:
  _target_: emg2qwerty.lightning.ConvVitCTCModule
  n_filters1: 32
  n_filters2: 128
  n_head: 8
  n_layers: 2

datamodule:
  _target_: emg2qwerty.lightning.WindowedEMGDataModule
  window_length: 8000
  padding: [1800, 200]
